version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=e-commerce
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: