import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavbarComponent from '@/components/NavbarComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen bg-background font-sans antialiased __className_343187'>
        <NavbarComponent />
        <main className="md:container relative flex min-h-screen flex-col bg-background">
          {children}
        </main>
        <footer className="py-6 md:px-8 md:py-0 bg-slate-400 mt-10">
          <div className="container flex flex-col items-center justify-between gap-4 md:h-24 md:flex-row">
            <p className="text-balance text-center text-2xl leading-loose text-muted-foreground md:text-left">Footer</p>
          </div>
        </footer>
      </body>
    </html>
  )
}
